### ISSUE TITLE
Regression: Adding jar to classpath at runtime in TestListenerAdapter fails in 6.9.6 but works in 6.9.4

### ISSUE THREAD

**Issue by TheLQ** [cbeust/testng#810]
I need to load a platform specific jar (Eclipse SWT) at runtime. My Maven config looks like this

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-surefire-plugin</artifactId>
	<version>2.18.1</version>
	<configuration>
		<!-- However initSWT SHOULD be called -->
		<classpathDependencyExcludes>
			<classpathDependencyExcludes>org.eclipse.swt:org.eclipse.swt.win32.win32.x86</classpathDependencyExcludes>
			<classpathDependencyExcludes>org.eclipse.swt:org.eclipse.swt.win32.win32.x86_64</classpathDependencyExcludes>
			<classpathDependencyExcludes>org.eclipse.swt:org.eclipse.swt.gtk.linux.x86</classpathDependencyExcludes>
			<classpathDependencyExcludes>org.eclipse.swt:org.eclipse.swt.gtk.linux.x86_64</classpathDependencyExcludes>
			<classpathDependencyExcludes>org.eclipse.swt:org.eclipse.swt.cocoa.macosx.x86_64</classpathDependencyExcludes>
		</classpathDependencyExcludes>
		<properties>
			<!-- See class for details -->
			<property>
				<name>listener</name>
				<value>org.brailleblaster.BBTestInit</value>
			</property>
		</properties>
	</configuration>
</plugin>
```

BBTestInit is a TestListenerAdapter which in it's constructor adds the correct jar to the classpath. I've also tried it when overriding onStart and onConfigurationSuccess. All fail in 6.9.6 and 6.9.5 with

```
java.lang.NoClassDefFoundError: org/eclipse/swt/widgets/Widget
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.privateGetPublicMethods(Class.java:2902)
at java.lang.Class.getMethods(Class.java:1615)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.hasJunit4TestAnnotation(TestNGDirectoryTestSuite.java:238)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.isJunit4Test(TestNGDirectoryTestSuite.java:226)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.isJUnitTest(TestNGDirectoryTestSuite.java:221)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:127)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.widgets.Widget
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 13 more
```

Once again in 6.9.4 this works without issues. I think this might be related to #691 but I'm not familiar enough with TestNG internals to know for sure. 

Is this method of runtime classpath adding no longer supported? What's the proper way to do this?

**Comment by TheLQ** [comment]
I should clarify none of the methods or fields have SWT classes in the TestListenerAdapter  nor in the class that contains the code below which would trigger a classload. This is what load's the JAR

```
URL url = swtFile.toURI().toURL();
URLClassLoader urlClassLoader = (URLClassLoader) ClassLoader.getSystemClassLoader();
Class<?> urlClass = URLClassLoader.class;
Method method = urlClass.getDeclaredMethod("addURL", new Class<?>[]{URL.class});
method.setAccessible(true);
method.invoke(urlClassLoader, new Object[]{url});
```

**Comment by juherr** [comment]
The stacktrace doesn't show any testng class. It's difficult to a say it's a TestNG issue. 

Then, you are not supposed to modify the classloader with TestNG... It worked before due to the issue you pointed. 

Why not using maven profiles where you add the appropriate dependencies depending on the system?

**Comment by TheLQ** [comment]
I've narrowed it down as far as I can, it's always reproducible by changing the TestNG version. Surefire was released in December 2014, before 6.9.4, so AFAIK there's no version specific checks. 

The reason we do this is because we release a platform-independent zip which contains all the platform-specific JARs, and the right one is loaded at runtime. Maven profile's won't help with that (and means we wouldn't be testing the loading code), and anyway we've had many issues in the past with 64bit/32bit detection. 

Would TestNG.addClassLoader() help? I just don't know how to get the TestNG object

**Comment by juherr** [comment]
It appears surefire is not able to find the class. 

As I understand:
Before, TestNG and surefire shared the same classloader. 
After, they have their own class loader. 

IMO, surefire should not look for the class. That's why I suppose it is more a surefire issue then a TestNG one, even if we didn't see it before.

**Comment by TheLQ** [comment]
Should I open a issue with surefire then?

**Comment by juherr** [comment]
Yes, I suppose.

@Tibor17 What do you think?

**Comment by Tibor17** [comment]
The surefire configuration starts just one forked jvm similar to starting a console application `java -cp ...`. We do not make Test class lookup in ClassLoader. The only thing we are doing and we always did was to start SurefireProvider via context ClassLoader `Thread.currentThread().getContextClassLoader()` which should, in normal circumstances, refer to System ClassLoader.
I strongly believe some Mock frameworks created some proxy objects, due to AOP,  over your classes and changed the context ClassLoader in current Thread.
If you take a look into the change `https://github.com/msebire/testng/commit/f9baca06535476cacb322db5eff710d31b5199ff` you will see that the variable `m_serviceLoaderClassLoader` was still used in 6.9.4 without knowing anything about current Thread context ClassLoader. Which means NULL would refer to System ClassLoader with classes the surefire loaded with your tests and listeners. After 6.9.5 the classloader is taken from current Thread context where the Mock/AOP frameworks store their classloader. It depends on that classloader how it is implemented. If it takes the parent contextx or system ClassLoader, then everything should work.

In such cases like this one I would build up a little project with Maven and totally isolate all dependencies. Then I would add tests with empty imports section, no dependencies like SWT, and test the listener if responds. Then I would add dependency by dependency in POM an extend the import section and write a little implementation. All should be done with small steps and some dependency or your code would be found as the root cause.

**Comment by TheLQ** [comment]
I have a simple example here to reproduce the problem with a simpler commons-lang3 dependency: https://github.com/TheLQ/testng810 . The pom contains a profile to include commons lang, and another to exclude it. Both set the listener property to InitListener which is a TestListenerAdapter and will load the commons-lang jar if it's not on the classpath. There is a simple test SomeTest with a method that returns the Commons lang Stopwatch class.

I'm running the following 4 commands
```
$ mvn clean install -Dtestng.version=6.9.4 -DincludeCommonsLang=true
$ mvn clean install -Dtestng.version=6.9.4 -DincludeCommonsLang=false
$ mvn clean install -Dtestng.version=6.9.6 -DincludeCommonsLang=true
$ mvn clean install -Dtestng.version=6.9.6 -DincludeCommonsLang=false
```

Here's the output (I've removed the irrelevant bits of maven compiling the classes) on my machine
```
$ mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T07:57:37-04:00)
Maven home: /home/leon/projects/bin/maven
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /home/leon/projects/bin/jdk1.8.0_60_x64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.1.0-2-amd64", arch: "amd64", family: "unix"

$ mvn clean install -Dtestng.version=6.9.4 -DincludeCommonsLang=true
...
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ testng810 ---
[INFO] Surefire report directory: /home/leon/test/testng810/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running testng810.SomeTest
Configuring TestNG with: TestNG652Configurator
Running init
Classpath (contains commons-lang3 true) /home/leon/test/testng810/target/test-classes:/home/leon/test/testng810/target/classes:/home/leon/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/home/leon/.m2/repository/org/testng/testng/6.9.4/testng-6.9.4.jar:...
Skipping adding commons-lang jar to classpath as its already on there
Test ran!
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.178 sec - in testng810.SomeTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
...

$ mvn clean install -Dtestng.version=6.9.4 -DincludeCommonsLang=false
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running testng810.SomeTest
Configuring TestNG with: TestNG652Configurator
Running init
Classpath (contains commons-lang3 false) /home/leon/test/testng810/target/test-classes:/home/leon/test/testng810/target/classes:/home/leon/.m2/repository/org/testng/testng/6.9.4/testng-6.9.4.jar:/home/leon/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar:/home/leon/.m2/repository/com/beust/jcommander/1.48/jcommander-1.48.jar:/home/leon/.m2/repository/org/apache/maven/surefire/surefire-testng-utils/2.18.1/surefire-testng-utils-2.18.1.jar:/home/leon/.m2/repository/org/apache/maven/surefire/surefire-grouper/2.18.1/surefire-grouper-2.18.1.jar:
Adding commons-lang3 to classpath
Test ran!
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.183 sec - in testng810.SomeTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
...

$ mvn clean install -Dtestng.version=6.9.6 -DincludeCommonsLang=true
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running testng810.SomeTest
Configuring TestNG with: TestNG652Configurator
Running init
Classpath (contains commons-lang3 true) /home/leon/test/testng810/target/test-classes:/home/leon/test/testng810/target/classes:/home/leon/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/home/leon/.m2/repository/org/testng/testng/6.9.6/testng-6.9.6.jar:...
Skipping adding commons-lang jar to classpath as its already on there
Test ran!
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.178 sec - in testng810.SomeTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
...

$ mvn clean install -Dtestng.version=6.9.6 -DincludeCommonsLang=false
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running testng810.SomeTest

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.111 s
[INFO] Finished at: 2015-09-24T15:08:51-04:00
[INFO] Final Memory: 20M/237M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project testng810: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: org/apache/commons/lang3/time/StopWatch
[ERROR] at java.lang.Class.getDeclaredMethods0(Native Method)
[ERROR] at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[ERROR] at java.lang.Class.privateGetPublicMethods(Class.java:2902)
[ERROR] at java.lang.Class.getMethods(Class.java:1615)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.hasJunit4TestAnnotation(TestNGDirectoryTestSuite.java:238)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.isJunit4Test(TestNGDirectoryTestSuite.java:226)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.isJUnitTest(TestNGDirectoryTestSuite.java:221)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:127)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.time.StopWatch
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] ... 13 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by Tibor17** [comment]
I guess you need to run tests, first with commons-lang3 and later without it.
Surefire does not use own ClassLoader by default. If forkCount and forkMode is not used in surefire configuration, then single surefire process is used and system CL.

Why you are hacking ClassLoader `urlClass.getDeclaredMethod("addURL", new Class<?>[]{URL.class});?

I think nobody who knows Maven regular basis would be hacking the UrlClassLoader.
First of all use two Maven profiles with/out commons-lang3 dependency if you really need such experiment.
Remove UrlClassLoader hack because changing the URL path after the ClassLoader is being used in Thread context may not be expected. How can you expect that JVM did not close the UrlClassLoader on the surefire process startup, see `API: URLClassLoader#close()`.

My advice, just keep the dependency of commons-lang3 because your classes or other dependency obviously has reference to StopWatch class.

**Comment by TheLQ** [comment]
Because as I said above our app is distributed as a single platform independent zip that contains all the platform-specific jars, and the correct one is loaded at runtime. We've had many problem's in the past with profile's and 32bit/64bit detection, and anyway profile's won't solve how the end user (not the developer) loads their platform-specific JAR nor testing that functionality.

I agree the reflection is hacky, but it's the only way I've found to reliably accomplish the above goal. Closing classloader's is an issue we haven't run into in practice. If you have an alternative non-hacky way to load JARs at runtime I'd love to hear them.

**Comment by Tibor17** [comment]
try to add jar file to CL like this
http://maven.apache.org/surefire/maven-surefire-plugin/examples/configuring-classpath.html

**Comment by Tibor17** [comment]
you can you maven-failsafe-plugin with multiple executions in the Maven phase integration-tests and verify

**Comment by juherr** [comment]
@TheLQ You should definitely try again to use profiles [activated by os and arch](http://maven.apache.org/enforcer/enforcer-rules/requireOS.html).

**Comment by Tibor17** [comment]
@TheLQ 
You are too quite. Does it mean that you have realized a solution?

**Comment by TheLQ** [comment]
Like I said, I'm well aware of maven profile's, when I tried them before it didn't work on anybody's elses machine that ran Eclipse. I tried for a few days but the only 100% reliable solution was runtime adding of platform-specific JARs. And because 5 people couldn't figure it out and couldn't work because they all ran Eclipse, that's the solution I went with.

maven-failsafe-plugin is an interesting option that I didn't think of. I'll report back when I have time to implement it.

**Comment by juherr** [comment]
@TheLQ Any news about it?

**Comment by TheLQ** [comment]
TestNG 6.9.9 and the following config
```
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.19</version>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<classpathDependencyExcludes>
						<classpathDependencyExcludes>org.apache.commons:commons-lang3</classpathDependencyExcludes>
					</classpathDependencyExcludes>
					<properties>
						<property>
							<name>listener</name>
							<value>testng810.InitListener</value>
						</property>
					</properties>
				</configuration>
			</plugin>
```

fails with 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19:integration-test (default) on project testng810: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19:integration-test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: org/apache/commons/lang3/time/StopWatch
[ERROR] at java.lang.Class.getDeclaredMethods0(Native Method)
[ERROR] at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[ERROR] at java.lang.Class.privateGetPublicMethods(Class.java:2902)
[ERROR] at java.lang.Class.getMethods(Class.java:1615)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.hasJunit4TestAnnotation(TestNGDirectoryTestSuite.java:257)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.isJunit4Test(TestNGDirectoryTestSuite.java:245)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.isJUnitTest(TestNGDirectoryTestSuite.java:240)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:132)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:118)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.time.StopWatch
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

So even with the Failsafe plugin it doesn't work. It looks like they share code anyway so it makes sense.

However I have managed to get profiles working without the "Cannot load 64-bit SWT libraries on 32-bit JVM" Exception I was getting before. My only issue with this is the SWT JAR loading code isn't unit tested but for my specific case I'm comfortable manually testing on various platforms. 

@Tibor17 I still wonder how replacing runtime JAR loading with profiles would solve the issue of end users loading the correct platform-specific JAR. Are my end users supposed to run Maven? Am I supposed to completely change my deployment process and distribute 5 individual platform-specific releases? Don't the big app servers like Tomcat auto-load JARs from a specific directory?

**Comment by Tibor17** [comment]
The config wanted the surefire to fail because it explicitly excluded
StopWatch class by
<classpathDependencyExcludes>org.apache.commons:commons-lang3/.
Such class is inside of JAR from ASF Commons.

>> Don't the big app servers like Tomcat auto-load JARs from a specific
directory?
You are on right way...
Is the customer using Application server (AS) of Tomcat for instance?
In general it's the best practice and ideal situation to suppose the AS is
a hardware for s/w engineer and the web archive is platform independent. I
only hardly remember Tomcat. AFAIK Tomcat has <TOMCAT_HOME>/endorsed for
addons libraries and catalina.properties file should enable such folder.
These libraries can be platform specific SWT/JavaFX/32bit/64bit etc.

>> Are my end users supposed to run Maven?
The real end user never.
The product vendor must use Maven - usually s/w development team or release
mgt.
I like the Maven because the modules and dependencies are the right thing
to specify project files in Eclipse/Netbeans/IDEA. The Maven project is
matching dependencies which is matched with the dependencies used by the
build. All the environment and IDE configuration is in one place - mean
Maven POM (many POM files and big structure). The developer can access some
POMs and release manager even more.
The only problem is with user of Maven because they do not always have
experiences with project setup.
In general Maven can do a lot. For instance you can use Bill Of Material
BOM, assembly plugin to modify the JAR/WAR content, profiles, etc.

>> Am I supposed to completely change my deployment process and distribute
5 individual platform-specific releases?

Definitely this I would do exactly. Means one platform for 32-bit another
for 64, etc.
You should not force single s/w to know about platform. Therefore platform
specific dependencies should not appear in project. Only common API should
be used in IDE and project, and the deployer should specify API
implementation (AS like JBOss/Tomcat, etc.) depending on whether it is
32/64bit or SWT/JavaFX whatever. Usually source code is only one but the
build process is multiple. This is also important for the cost computing of
the s/w development so that the s/w is one and human resources can be
limited in s/w development.
If we suppose the Tomcat is modified, depending on added platform
libraries, the developer can choose the one platform.

Cheers
Tibor


On Tue, Nov 24, 2015 at 6:54 PM, Leon Blakey <notifications@github.com>
wrote:

> TestNG 6.9.9 and the following config
>
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-failsafe-plugin</artifactId>
>                 <version>2.19</version>
>                 <executions>
>                     <execution>
>                         <goals>
>                             <goal>integration-test</goal>
>                             <goal>verify</goal>
>                         </goals>
>                     </execution>
>                 </executions>
>                 <configuration>
>                     <classpathDependencyExcludes>
>                         <classpathDependencyExcludes>org.apache.commons:commons-lang3</classpathDependencyExcludes>
>                     </classpathDependencyExcludes>
>                     <properties>
>                         <property>
>                             <name>listener</name>
>                             <value>testng810.InitListener</value>
>                         </property>
>                     </properties>
>                 </configuration>
>             </plugin>
>
> fails with
>
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19:integration-test (default) on project testng810: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19:integration-test failed: There was an error in the forked process
> [ERROR] java.lang.NoClassDefFoundError: org/apache/commons/lang3/time/StopWatch
> [ERROR] at java.lang.Class.getDeclaredMethods0(Native Method)
> [ERROR] at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> [ERROR] at java.lang.Class.privateGetPublicMethods(Class.java:2902)
> [ERROR] at java.lang.Class.getMethods(Class.java:1615)
> [ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.hasJunit4TestAnnotation(TestNGDirectoryTestSuite.java:257)
> [ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.isJunit4Test(TestNGDirectoryTestSuite.java:245)
> [ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.isJUnitTest(TestNGDirectoryTestSuite.java:240)
> [ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:132)
> [ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:118)
> [ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
> [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
> [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
> [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
> [ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.time.StopWatch
> [ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> [ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> [ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>
> So even with the Failsafe plugin it doesn't work. It looks like they share
> code anyway so it makes sense.
>
> However I have managed to get profiles working without the "Cannot load
> 64-bit SWT libraries on 32-bit JVM" Exception I was getting before. My only
> issue with this is the SWT JAR loading code isn't unit tested but for my
> specific case I'm comfortable manually testing on various platforms.
>
> @Tibor17 <https://github.com/Tibor17> I still wonder how replacing
> runtime JAR loading with profiles would solve the issue of end users
> loading the correct platform-specific JAR. Are my end users supposed to run
> Maven? Am I supposed to completely change my deployment process and
> distribute 5 individual platform-specific releases? Don't the big app
> servers like Tomcat auto-load JARs from a specific directory?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cbeust/testng/issues/810#issuecomment-159355451>.
>



-- 
Cheers
Tibor

**Comment by Tibor17** [comment]
>> Am I supposed to completely change my deployment process and distribute
5 individual platform-specific releases?
Do not get me wrong.
The s/w itself should be one and platform independent (WAR file). The
application server AS or executor should be multiple.
The customer should reach an installation CD for his deployment.
So you would have:
* WAR file
* AS or executor platform dependent
* individual customer deployment (installation instructions, shell scripts,
sql patches, best to have it automated with scripts, WAR, AS, for specific
customer environment). Not sure if you need this, but nowadays in cloud
world this is avoided as well. Of course I do not know your business and
requirements which might be very specific of course.

On Tue, Nov 24, 2015 at 6:54 PM, Leon Blakey <notifications@github.com>
wrote:

> TestNG 6.9.9 and the following config
>
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-failsafe-plugin</artifactId>
>                 <version>2.19</version>
>                 <executions>
>                     <execution>
>                         <goals>
>                             <goal>integration-test</goal>
>                             <goal>verify</goal>
>                         </goals>
>                     </execution>
>                 </executions>
>                 <configuration>
>                     <classpathDependencyExcludes>
>                         <classpathDependencyExcludes>org.apache.commons:commons-lang3</classpathDependencyExcludes>
>                     </classpathDependencyExcludes>
>                     <properties>
>                         <property>
>                             <name>listener</name>
>                             <value>testng810.InitListener</value>
>                         </property>
>                     </properties>
>                 </configuration>
>             </plugin>
>
> fails with
>
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19:integration-test (default) on project testng810: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19:integration-test failed: There was an error in the forked process
> [ERROR] java.lang.NoClassDefFoundError: org/apache/commons/lang3/time/StopWatch
> [ERROR] at java.lang.Class.getDeclaredMethods0(Native Method)
> [ERROR] at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> [ERROR] at java.lang.Class.privateGetPublicMethods(Class.java:2902)
> [ERROR] at java.lang.Class.getMethods(Class.java:1615)
> [ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.hasJunit4TestAnnotation(TestNGDirectoryTestSuite.java:257)
> [ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.isJunit4Test(TestNGDirectoryTestSuite.java:245)
> [ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.isJUnitTest(TestNGDirectoryTestSuite.java:240)
> [ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:132)
> [ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:118)
> [ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
> [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
> [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
> [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
> [ERROR] Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.time.StopWatch
> [ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> [ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> [ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>
> So even with the Failsafe plugin it doesn't work. It looks like they share
> code anyway so it makes sense.
>
> However I have managed to get profiles working without the "Cannot load
> 64-bit SWT libraries on 32-bit JVM" Exception I was getting before. My only
> issue with this is the SWT JAR loading code isn't unit tested but for my
> specific case I'm comfortable manually testing on various platforms.
>
> @Tibor17 <https://github.com/Tibor17> I still wonder how replacing
> runtime JAR loading with profiles would solve the issue of end users
> loading the correct platform-specific JAR. Are my end users supposed to run
> Maven? Am I supposed to completely change my deployment process and
> distribute 5 individual platform-specific releases? Don't the big app
> servers like Tomcat auto-load JARs from a specific directory?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cbeust/testng/issues/810#issuecomment-159355451>.
>



-- 
Cheers
Tibor

**Comment by TheLQ** [comment]
... You completely missed the point, I was using commons-lang3 as a simple an easily accessible example (per your request) since there's less going on than in SWT. I was also using an app server as an example of a app that loads JARs at runtime since you said "nobody does this". If that wasn't clear I'm sorry

Of course I know the advantages of developers using Maven, that's why I'm here. 

My use case is a desktop app using SWT that should easily run on both developers and users machines that have Windows (x86/64), Linux (x86/64), and Mac for a total of 5 platforms. To make the lives of end users and developers simpler and to follow true "write one run anywhere" I have a single zip release that anybody on any platform or arch can download and run. For installers it's also easier as any windows user regardless of x86 or 64 arch downloads the single Windows installer.

If I followed what your suggesting I would release 5 separate installers and 5 separate zip files for each platform I'm supporting. Maybe I can condense it down to 3 installers (1 per platform that has both JARs for both archs), but that still sounds many times more complicated and confusing than "everybody download this and run it" and some reflection code.

I'll take `URLClassLoader.addURL` and simple "runs anywhere" releases. If you have a less hacky alternative for an end user to load a platform-specific JAR I'd love to hear it.

---

Regardless this is derailing the point of this ticket. In my specific use case I have fixed the issue by duplicating the "load platform-specific JAR" functionality in Maven profiles. If the TestNG maintainers believe that loading JARs at runtime before tests should be impossible then go ahead and close this.

**Comment by juherr** [comment]
>  I have fixed the issue by duplicating the "load platform-specific JAR" functionality in Maven profiles.

It is the best solution :)

> If the TestNG maintainers believe that loading JARs at runtime before tests should be impossible then go ahead and close this.

As your need was due to an eclipse issue with maven profile (did you open an issue on eclipse?), I don't see any other use case. I close but we will reopen it if someone shows us a real use case some day.
